### ISSUE TITLE
Allow passing bounds to allow values greater than 1.0

### ISSUE THREAD

**Issue by bzf** [AlexChekel1337/SliderControl#2]
Similar to the [`Slider` in SwiftUI](https://developer.apple.com/documentation/swiftui/slider/init(value:in:oneditingchanged:)), I think it could be a nice addition to allow the user to pass in some `bounds: ClosedRange<V>` to be able to work with values greater than 1.0 instead of having to do that conversion manually when the value changes.

**Comment by AlexChekel1337** [comment]
Indeed! This control could use more SwiftUI-like APIs similar to built-in `Slider`. I will try to make it work soon.

**Comment by AlexChekel1337** [comment]
The functionality was implemented in [v2.1.0](https://github.com/AlexChekel1337/SliderControl/releases/tag/v2.1.0) release
